title: "Lekshmy Anoop"
description: "Student Leader | Debater | Future Attorney"
baseurl: ""
url: "https://lekshmyx.github.io"

theme: minima

author:
  name: "Lekshmy Anoop"
  email: "your-email@example.com"

github_username: lekshmyx
linkedin_username: yourprofile

markdown: kramdown
plugins:
  - jekyll-feed
